
project_name: jiboia

builds:
  - id: client
    main: ./cmd/jiboia-client
    binary: jiboia-client
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

  - id: relay
    main: ./cmd/jiboia-relay
    binary: jiboia-relay
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

  - id: server
    main: ./cmd/jiboia-server
    binary: jiboia-server
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - format: zip
    replacements:
      darwin: macOS
      amd64: x86_64
      arm64: arm64
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: valcinei
    name: jiboia-tunnel

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
