name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  goreleaser:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_RELAY_URL: ${{ secrets.DEFAULT_RELAY_URL }}

  docker:
    name: Build and Push Docker Images (Relay and Server)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}

          # Relay
          docker build -f Dockerfile.relay -t ${{ secrets.DOCKER_USERNAME }}/jiboia-relay:$VERSION -t ${{ secrets.DOCKER_USERNAME }}/jiboia-relay:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/jiboia-relay:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/jiboia-relay:latest

          # Server
          docker build -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/jiboia-server:$VERSION -t ${{ secrets.DOCKER_USERNAME }}/jiboia-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/jiboia-server:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/jiboia-server:latest
