name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build binaries
        run: |
          mkdir -p dist
          for CMD in jiboia-client jiboia-relay jiboia-server; do
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${CMD}-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/${CMD}
          done

      - name: Upload binaries
        uses: uses: actions/upload-artifact@v3.1.3
        with:
          name: jiboia-binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
